// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating personalized savings tips based on user spending patterns.
 *
 * - generateSavingsTips - A function that takes spending patterns as input and returns AI-generated savings tips.
 * - GenerateSavingsTipsInput - The input type for the generateSavingsTips function.
 * - GenerateSavingsTipsOutput - The return type for the generateSavingsTips function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSavingsTipsInputSchema = z.object({
  incomePatterns: z
    .string()
    .describe(
      'A detailed description of the user’s income patterns, including categories and amounts.'
    ),
  spendingPatterns: z
    .string()
    .describe(
      'A detailed description of the user’s spending patterns, including categories, amounts, and frequency.'
    ),
});
export type GenerateSavingsTipsInput = z.infer<typeof GenerateSavingsTipsInputSchema>;

const GenerateSavingsTipsOutputSchema = z.object({
  savingsTips: z
    .string()
    .describe('Personalized savings tips generated based on the provided spending patterns.'),
});
export type GenerateSavingsTipsOutput = z.infer<typeof GenerateSavingsTipsOutputSchema>;

export async function generateSavingsTips(
  input: GenerateSavingsTipsInput
): Promise<GenerateSavingsTipsOutput> {
  return generateSavingsTipsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSavingsTipsPrompt',
  input: {schema: GenerateSavingsTipsInputSchema},
  output: {schema: GenerateSavingsTipsOutputSchema},
  prompt: `Anda adalah seorang penasihat keuangan pribadi yang cerdas dan ramah. Tugas Anda adalah memberikan tips menabung yang dipersonalisasi dan dapat ditindaklanjuti dalam Bahasa Indonesia, berdasarkan data keuangan pengguna.

Analisis data pemasukan dan pengeluaran berikut untuk memberikan saran yang relevan.

Data Pemasukan:
{{{incomePatterns}}}

Data Pengeluaran:
{{{spendingPatterns}}}

Berikan beberapa tips konkret yang dapat membantu pengguna mengelola uang mereka dengan lebih baik. Fokus pada area pengeluaran terbesar dan berikan saran praktis. Jika ada pemasukan dari berbagai sumber, berikan saran tentang cara mengoptimalkannya.

Tips Menabung:`,
});

const generateSavingsTipsFlow = ai.defineFlow(
  {
    name: 'generateSavingsTipsFlow',
    inputSchema: GenerateSavingsTipsInputSchema,
    outputSchema: GenerateSavingsTipsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
